# Generated by Django 3.2.5 on 2022-04-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.TextField(default=' ', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='profile',
            name='descript',
            field=models.TextField(default=' ', verbose_name='descript'),
        ),
        migrations.AddField(
            model_name='profile',
            name='spec',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Программирование'), (2, 'Музыка'), (3, 'Блоги и видео')], default=1, verbose_name='spec'),
        ),
    ]
