# Generated by Django 3.2.5 on 2022-04-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20220408_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default=' ', max_length=50, verbose_name='city'),
        ),
    ]
