# Generated by Django 3.2.5 on 2022-04-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='spec',
            field=models.PositiveSmallIntegerField(choices=[('Программирование', 'Программирование'), ('Музыка', 'Музыка'), ('Блоги и видео', 'Блоги и видео')], default=1, verbose_name='spec'),
        ),
    ]
