# Generated by Django 3.2.5 on 2022-04-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_profile_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='spec',
            field=models.PositiveSmallIntegerField(choices=[('Программирование', 'Программирование'), ('Музыка', 'Музыка'), ('Музыка', 'Блоги и видео')], default=1, verbose_name='spec'),
        ),
    ]
