# Generated by Django 3.2.5 on 2022-04-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_profile_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/profile_images/default_picture.png', upload_to='static/profile_images'),
        ),
    ]
