# Generated by Django 3.2.5 on 2022-04-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='spec',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Программирование'), (2, 'Музыка'), (3, 'Блоги и видео')], verbose_name='spec'),
        ),
    ]
