# Generated by Django 3.2.5 on 2022-05-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_profile_spec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={},
        ),
        migrations.AlterField(
            model_name='friends',
            name='friend',
            field=models.IntegerField(default=True, verbose_name='friend_id'),
        ),
    ]
